Add support for the `canon` output format
hpcc-systems/hpcc-js-wasm pull request #269
Opened 2024-09-14 16:16 UTC by tmr232

Support the [`canon`](https://graphviz.gitlab.io/docs/outputs/canon/) format, to allow formatting DOT files without performing any layout.

This works today, but the type-checker is not happy about it. So I want to add it to the `Format` options.

2024-09-16 09:58 UTC, GordonSmith requested changes

2024-09-16 09:58 UTC, GordonSmith commented on packages/graphviz/src/graphviz.ts
> +export type Format = "svg" | "dot" | "json" | "dot_json" | "xdot_json" | "plain" | "plain-ext" | "canon";
Can you also add here:  https://github.com/hpcc-systems/hpcc-js-wasm/blob/trunk/packages/graphviz/test/graphviz.ts 

Thx for the PR!!!

2024-09-17 11:36 UTC, merged

2024-09-17 11:37 UTC, GordonSmith reviewed
Look good - thx!

2024-09-17 12:14 UTC, tmr232 commented
Thanks for the super fast response!